format: 'bestaudio/best'
outtmpl: 'main/static/music/%(title)s.%(ext)s'
restrictfilenames: Yes
nocheckcertificate: Yes
ignoreerrors: No
logtostderr: No
quiet: Yes
no_warning: Yes
default_search: 'auto'
source_address: '0.0.0.0'
