format: 'bestaudio/best'
outtmpl: 'main/static/music/%(title)s.%(ext)s'
restrictfilenames: yes
nocheckcertificate: yes
ignoreerrors: n
logtostderr: n
quiet: yes
no_warning: yes
default_search: auto
source_address: '0.0.0.0'